language: node_js
node_js:
  - 'stable'
cache: yarn
install:
  - yarn install
jobs:
  include:
    - stage: build and deploy
      script:
        - yarn build
      deploy:
        provider: npm
        skip_cleanup: true
        email: $NPM_EMAIL
        api_key: $NPM_TOKEN
        on:
          tags: true
    - stage: storybook
      script:
        - npm i --save-dev webpack-cli
        - npm run build-storybook
      deploy:
        provider: pages
        skip-cleanup: true
        local_dir: storybook-static
        github-token: $GITHUB_TOKEN
        keep-history: true
        target_branch: gh-pages
        on:
          branch: develop