const TEXT =
  "Messieurs,\r\n" +
  "\r\n" +
  "Votre fondateur mit dans votre établissement toute la noblesse et la grandeur de son ame ; il voulut que vous fussiez toujours libres et égaux. En effet, il dut élever au-dessus de la dépendance, des hommes qui étoient au-dessus de l’intérêt, et qui, aussi généreux que lui, faisoient aux Lettres l’honneur qu’elles méritent, de les cultiver pour elles-mêmes. Il étoit peut-être à craindre qu’un jour des travaux si honorables ne se ralentissent. Ce fut pour les conserver dans leur vigueur que vous vous fîtes une règle de n’admettre aucun Académicien, qui ne résidât dans Paris. Vous vous êtes écartés sagement de cette loi, quand vous avez reçu de ces génies rares que leurs dignités appeloient ailleurs, mais que leurs ouvrages touchans ou sublimes rendoient toujours présens parmi vous ; car ce seroit violer l’esprit d’une loi, que de n’en pas transgresser la lettre en faveur des grands hommes. Si feu M. le président Bouhier, après s’être flatté de vous consacrer ses jours, fut obligé de les passer loin de vous, l’Académie et lui se consolèrent, parce qu’il n’en cultivoit pas moins vos sciences dans la ville de Dijon, qui a produit tant d’hommes de lettres, et où le mérite de l’esprit semble être un des caractères des citoyens." +
  "Il faisoit ressouvenir la France de ces temps où les plus austères Magistrats, consommés, comme lui, dans l’étude des lois, se délassoient des fatigues de leur état dans les travaux de la littérature. Que ceux qui méprisent ces travaux aimables ; que ceux qui mettent je ne sais quelle misérable grandeur à se renfermer dans le cercle étroit de leurs emplois, sont à plaindre ! Ignorent-ils que Cicéron, après avoir rempli la première place du monde, plaidoit encore les causes des citoyens, écrivoit sur la nature des Dieux, conféroit avec des philosophes ; qu’il alloit au théâtre ; qu’il daignoit cultiver l’amitié d’Esopus et de Roscius, et laissoit aux petits esprits leur constante gravité, qui n’est que le masque de la médiocrité ?" +
  "M. le président Bouhier étoit très-savant ; mais il ne ressembloit pas à ces savans insociables et inutiles, qui négligent l’étude de leur propre langue, pour savoir imparfaitement des langues anciennes ; qui se croient en droit de mépriser leur siècle, parce qu’ils se flattent d’avoir quelques connoissances des siècles passés ; qui se récrient sur un passage d’Eschyle, et n’ont jamais eu le plaisir de verser des larmes à nos spectacles." +
  "Il traduisit le poème de Pétrone sur la guerre civile ; non qu’il pensât que cette déclamation, pleine de pensées fausses, approchât de la sage et élégante noblesse de Virgile : il savoit que la satire de Pétrone, quoique semée de traits charmans, n’est que le caprice d’un jeune homme obscur, qui n’eut de frein ni dans ses mœurs, ni dans son style. Des hommes qui se sont donnés pour des maîtres de goût et de volupté, estiment tout dans Pétrone ; et M. Bouhier, plus éclairé, n’estime pas même tout ce qu’il a traduit : c’est un des progrès de la raison humaine dans ce siècle, qu’un traducteur ne soit plus idolâtre de son auteur, et qu’il sache lui rendre justice comme à un contemporain." +
  "Il exerça ses talens sur ce poème, sur l’hymne à Vénus, sur Anacréon, pour montrer que les poètes doivent être traduits en vers : c’étoit une opinion qu’il défendoit avec chaleur, et on ne sera pas étonné que je me range à son sentiment.\r\n" +
  "Qu’il me soit permis, Messieurs, d’entrer ici avec vous dans ces discussions littéraires ; mes doutes me vaudront de vous des décisions. C’est ainsi que je pourrai contribuer aux progrès des arts ; j’aimerois mieux prononcer devant vous un discours utile qu’un discours éloquent." +
  "Pourquoi Homère, Théocrite, Lucrèce, Virgile, Horace sont-ils heureusement traduits chez les Italiens et chez les Anglois ? Pourquoi ces Nations n’ont-elles aucun grand Poète de l’antiquité en prose, et que nous n’en avons encore eu aucun en vers ? Je vais tâcher d’en démêler la raison." +
  "La difficulté, surmontée dans quelque genre que ce puisse être, fait une grande partie du mérite. Point de grandes choses sans de grandes peines ; et il n’y a point de Nation au monde chez laquelle il soit plus difficile que chez la nôtre, de rendre une véritable vie à la poésie ancienne." +
  "Les premiers Poètes formèrent le génie de leur langue ; les Grecs et les Latins employèrent d’abord la poésie à peindre les objets sensibles de toute la nature. Homère exprime tout ce qui frappe les yeux ; les François, qui n’ont guère commencé à perfectionner la grande poésie qu’au théâtre, n’ont pu et n’ont dû exprimer alors que ce qui peut toucher l’ame." +
  "Nous nous sommes interdit nous-mêmes insensiblement presque tous les objets que d’autres Nations ont osé peindre. Il n’est rien que le Dante n’exprimât, à l’exemple des anciens : il accoutuma les Italiens à tout dire ; mais nous, comment pourrions-nous aujourd’hui imiter l’auteur des Géorgiques, qui nomme sans détour tous les instrumens de l’agriculture ? À peine les connoissons-nous ; et notre mollesse orgueilleuse dans le sein du repos et du luxe de nos villes, attache malheureusement une idée basse à ces travaux champêtres et au détail de ces arts utiles, que les maîtres et les législateurs de la terre cultivoient de leurs mains victorieuses." +
  "Si nos bons Poètes avoient su exprimer heureusement les petites choses, notre langue ajouteroit aujourd’hui ce mérite, qui est très-grand, à l’avantage d’être devenue la première langue du monde, pour les charmes de la conversation et pour l’expression du sentiment. Le langage du cœur et le style du théâtre ont entièrement prévalu. Ils ont embelli la langue françoise ; mais ils en ont resserré les agréments dans des bornes un peu étroites.\r\n" +
  "Et quand je dis ici, Messieurs, que ce sont les grands Poètes qui ont déterminé le génie des langues, je n’avance rien qui ne soit connu de vous. Les Grecs n’écrivirent l’histoire que quatre cents ans après Homère. La langue grecque reçut, de ce grand peintre de la nature, la supériorité qu’elle prit chez tous les peuples de l’Asie et de l’Europe : c’est Térence qui, chez les Romains, parla le premier avec une pureté toujours élégante : c’est Pétrarque qui, après le Dante, donna à la langue italienne cette aménité et cette grace qu’elle a toujours conservées. C’est à Lopez de Vega que l’Espagnol doit sa noblesse et sa pompe : c’est Shakespear, qui, tout barbare qu’il étoit, mit dans l’anglois cette force et cette énergie qu’on n’a jamais pu augmenter depuis sans l’outrer, et par conséquent, sans l’affoiblir. D’où vient ce grand effet de la poésie, de former et de fixer enfin le génie des peuples et de leurs langues ? La cause en est bien sensible : les premiers bons vers, ceux même qui n’en ont que l’apparence, s’impriment dans la mémoire, à l’aide de l’harmonie. Leurs tours naturels et hardis deviennent familiers ; les hommes, qui sont tous nés imitateurs, prennent insensiblement la manière de s’exprimer, et même de penser, des premiers dont l’imagination a subjugué celle des autres. Me désavouerez vous donc, Messieurs, quand je dirai que le vrai mérite et la réputation de notre langue ont commencé à l’auteur du Cid et de Cinna ?\r\n" +
  "Montagne, avant lui, étoit le seul livre qui attirât l’attention du petit nombre d’étrangers qui pouvoient savoir le françois ; mais le style de Montagne n’est ni pur, ni correct, ni précis, ni noble : il est énergique et familier : il exprime naïvement de grandes choses : c’est cette naïveté qui plaît ; on aime le caractère de l’auteur ; on se plaît à se retrouver dans ce qu’il dit de lui même, à converser, à changer de discours et d’opinion avec lui. J’entends souvent regretter le langage de Montagne, c’est son imagination qu’il faut regretter : elle étoit forte et hardie ; mais sa langue étoit bien loin de l’être.\r\n" +
  "Marot, qui avoit formé le langage de Montagne, n’a presque jamais été connu hors de sa patrie ; il a été goûté parmi nous pour quelques contes naïfs, pour quelques épigrammes licencieuses, dont le succès est presque toujours dans le sujet : mais c’est par ce petit mérite même que la langue fut long-temps avilie. On écrivoit dans ce style les tragédies, les poèmes, l’histoire, les livres de morale.\r\n" +
  "Le judicieux Despréaux a dit : imitez de Marot l’élégant badinage ; j’ose croire qu’il auroit dit : naïf badinage, si ce mot plus vrai n’eût rendu son vers moins coulant. Il n’y a de véritablement bons ouvrages, que ceux qui passent chez les nations étrangères, qu’on y apprend, qu’on y traduit : et chez quel peuple a-t-on jamais traduit Marot ?\r\n";

export default TEXT;
